language: go

go:
  - 1.15

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y \
    gcc \
    gfortran \
    libopenmpi-dev \
    libhwloc-dev \
    liblapacke-dev \
    libopenblas-dev \
    libmetis-dev \
    libsuitesparse-dev \
    libmumps-dev \
    libfftw3-dev \
    libfftw3-mpi-dev

notifications:
  email:
    recipients:
      - dorival.pedroso@gmail.com
    on_success: never
    on_failure: always
